name: MoscowRealty
options:
  bundleIdPrefix: com.baha
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Debug
settings:
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  MoscowRealty:
    type: application
    platform: iOS
    sources:
      - path: MoscowRealty
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.baha.moscowrealty
      INFOPLIST_FILE: MoscowRealty/Info.plist
    info:
      path: MoscowRealty/Info.plist
      properties:
        CFBundleName: МоскваРиелти
        CFBundleDisplayName: МоскваРиелти
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: "Для отображения квартир на карте"
  MoscowRealtyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MoscowRealtyTests
    dependencies:
      - target: MoscowRealty
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.baha.moscowrealtyTests
